### ISSUE TITLE
NFB Videos Won't Open

### ISSUE THREAD

**Issue by missjane63** [jbinkley60/plugin.video.nfbca#1]
Getting the nfb.ca and generic Kodi Playback error when trying to play some videos in the Based on Childrens' Books category.  I checked the website and they both play there.  I haven't checked to see what other videos may not play...  Did a quick check, several other vids in the category won't play.

[I Want a Dog](https://www.nfb.ca/film/i_want_a_dog/)
[The Girl Who Hated Books](https://www.nfb.ca/film/girl_who_hated_books/)

Kodi 20/Win 7/Addon version 0.0.990e/Using new t1mlib

Tks

**Comment by jbinkley60** [comment]
I am sorry I missed your earlier issue.  I checked these and they are the same as issue #2.
